### PR TITLE
fix start issue

### LINKED ISSUE #73: [3 zypak-helper] Invalid fd assignment: /app/Icalingua++/icalingua
OS: Arch Linux
HOW:
```
flatpak update
flatpak install io.github.Icalingua.Icalingua
flatpak run -v io.github.Icalingua.Icalingua
```

### PR DESCRIPTION
**Pull request by madoka773**
fix #73

### CODE REVIEW

**Comment by madoka773** [comment]
@clansty 可以了

**Comment by madoka773** [comment]
Related https://github.com/refi64/zypak/commit/0d88cfc40fd5cbbd780bd8de7da1eb24529f4173

**Comment by clansty** [comment]
怎么发

**Comment by madoka773** [comment]
@clansty  https://github.com/flathub/flathub/issues/4978 类似这样的

**Pull request merged**
